Laravel Project Education Center/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|register_adult
*/

Route::group(['middleware' => ['auth']], function () {
	Route::resource("feedback","FeedbackController");
	Route::get('/home', function () {
	    return view('home');
	});
});

Route::group(['middleware' => ['auth','customer']], function () {
	Route::get("allcourses","CourseController@allcourses"); 
	Route::get("customercourses/{key}","CourseController@customercourses"); 
	Route::get("allcamps","CustomerController@allcamps"); 
	Route::get("customercamps","CustomerController@customercamps"); 
	Route::get("customerconsultation","CustomerController@customerconsultation"); 
	Route::get("allconsultation","CustomerController@allconsultation"); 
	
	Route::get('/error', function()
	{
	   return view('errors');
	});

	Route::get("user_programs/{key}","ProgramController@user_programs");
	Route::get("view_course/{key}","ProgramController@view_course");

}); 

	Route::group(['middleware' => ['auth','admin']], function () {
		Route::resource("course_menus","CourseMenuController"); 
	Route::resource("menus","MenuController");
	Route::post("new_customer","UserController@create"); 
	Route::get("customers_user/{key}", function () {
	    return view('users.create');
	}); 
	Route::post("customers_adult","CustomerController@customers_adult"); 
	Route::get("/adult_application_create","AdultController@createApplication"); 
	Route::post("/adult_application_store","AdultController@storeApplication")->name("adult.application.store"); 
	Route::get("/kid_application_create","KidController@createApplication"); 
	Route::post("/kid_application_store","KidController@storeApplication")->name("kid.application.store"); 

	Route::get('/register_adult', function () {
		//$howKnows = App\HowKnow::all();
		//$jobs=App\Job::orderBy("id","asc")->get();,compact("howKnows","jobs");
	    return view('customers.register_adult');
	}); 
	Route::resource("users","UserController"); 
	Route::resource("customers","CustomerController"); 
	Route::resource("kids","KidController"); 
	Route::resource("departments","DepartmentController");
	Route::resource("parents","ParentController");
	Route::resource("kid_parents","KidParentController");
	Route::resource("jobs","JobController");
	Route::resource("adults","AdultController");
	Route::resource("adult_jobs","AdultJobController");
	Route::resource("courses","CourseController"); 
	Route::resource("favorites","FavoriteController");
	Route::resource("programs","ProgramController");
	Route::get("course_programs/{key}","ProgramController@course_programs");


	Route::resource("roles","RoleController");
	Route::resource("employees","EmployeeController"); 
	Route::resource("program_employees","ProgramEmployeeController");
	Route::resource("department_employees","DepartmentEmployeeController");
	Route::resource("customer_programs","CustomerProgramController");
	Route::get("customer_program/{key}","CustomerProgramController@listbyProgram");
	Route::get("how_know_customers/{key}","CustomerController@listByHowKnow");
	Route::resource("how_knows","HowKnowController");
	Route::get('/dashboard', function () {
	    return view('welcome');
	});
	Route::get('/page-error', function()
	{
	   return view('error-admin');
	});
	Route::resource("levels","LevelController");
	Route::resource("lectures","LectureController");
	Route::resource("program_levels","ProgramLevelController");
	Route::resource("lecture_customer_programs","LectureCustomerProgramController");
	//Route::get('/home', 'HomeController@index');
});
Auth::routes();
Route::get('/', function()
	{
	   return view('auth.login');
	});
Route::get('logout', array('uses' => 'HomeController@logout'));

Laravel Project Education Center/resources/views/courses/create.blade.php
@extends('layouts.admin')

@section('header')
   <h3 class="panel-title"><i class="glyphicon glyphicon-plus"></i> دورة جديد</h3>
@endsection
@section('css')
<style type="text/css">
.field{
  margin-bottom: 10px;
}
.btn-group{
  width: 5%;
}
</style>
@endsection

@section('content')
    @include('error')
    <form class="form-horizontal" action="{{ route('courses.store') }}" method="POST">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-body">
            @include('error')
            <div class="form-group @if($errors->has('name')) has-error @endif">
              <label class="col-sm-3 text-left">إسم الدورة:<span class="asterisk"> *</span></label>
              <div class="col-sm-6">
                   <input required class="form-control" name="name" placeholder="أدخل اسم الدورة" value="{{ old('name') }}">
                    @if($errors->has("name"))
                      <span class="help-block">{{ $errors->first("name") }}</span>
                    @endif
              </div>
            </div>
            <div class="form-group @if($errors->has('department')) has-error @endif">
              <label class="col-sm-3 text-left" for="department-field">القسم:<span class="asterisk"> *</span></label>
              <div class="col-sm-6">
                <select id="department-field" name="department" class="form-control" >
                  <option value="0">Choose</option>
                  @foreach($departments as $department)
                    <option value="{{$department->id}}">{{$department->name}}</option>
                  @endforeach
                </select>
                @if($errors->has("department"))
                  <span class="help-block">{{ $errors->first("department") }}</span>
                @endif
              </div>
            </div>
            <div class="form-group @if($errors->has('description')) has-error @endif">
              <label class="col-sm-3 text-left">نبذه عن الدورة:</label>
              <div class="col-sm-6">
                   <textarea  name="description" class="form-control" rows="3"></textarea>
                     @if($errors->has("description"))
                      <span class="help-block">{{ $errors->first("description") }}</span>
                     @endif
              </div>
            </div>
            <!-- <div class="form-group @if($errors->has('goals')) has-error @endif">
              <label class="col-sm-3 text-left" for="goals-field">الأهداف:</label>
              <div class="col-sm-6 control-group" id="fields">
                  <input data-items="8" name="goals[]" class="form-control"/>
                  @if($errors->has("goals"))
                    <span class="help-block">{{ $errors->first("goals") }}</span>
                  @endif
              </div>
              <button class="btn btn-success" type="button">+</button>
            </div> -->
            <div class="form-group @if($errors->has('goals')) has-error @endif">
              <label class="col-sm-3 text-left" for="goals-field">الاهداف:</label>
              <input type="hidden" id="count" value="1" />
              <div class="feild-group col-sm-6">
                <input id="field1"  data-items="8" name="goals[]" class="field form-control"/>
              </div>
              <div class="btn-group col-sm-1">
                <button id="btn1" class="field form-control btn btn-success add-more">+</button>
              </div>
               @if($errors->has("goals"))
                <span class="help-block">{{ $errors->first("goals") }}</span>
               @endif
            </div>

             <div class="form-group @if($errors->has('age')) has-error @endif">
                <label class="col-sm-3 text-left">المرحلة العمرية:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="age" value="{{ old('age') }}">
                      @if($errors->has("age"))
                        <span class="text-muted help-block">{{ $errors->first("age") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('duration')) has-error @endif">
                <label class="col-sm-3 text-left">المدة الزمنية:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="duration" value="{{ old('duration') }}">
                      @if($errors->has("duration"))
                        <span class="text-muted help-block">{{ $errors->first("duration") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('levels')) has-error @endif">
                <label class="col-sm-3 text-left">المستويات:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="levels" value="{{ old('levels') }}">
                      @if($errors->has("levels"))
                        <span class="text-muted help-block">{{ $errors->first("levels") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('tutorials')) has-error @endif">
                <label class="col-sm-3 text-left">المناهج المستخدمه:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="tutorials" value="{{ old('tutorials') }}">
                      @if($errors->has("tutorials"))
                        <span class="text-muted help-block">{{ $errors->first("tutorials") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_performance')) has-error @endif">
                <label class="col-sm-3 text-left">كيفية التقييم:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_performance" value="{{ old('how_performance') }}">
                      @if($errors->has("how_performance"))
                        <span class="text-muted help-block">{{ $errors->first("how_performance") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_register')) has-error @endif">
                <label class="col-sm-3 text-left">شروط التسجيل:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_register" value="{{ old('how_register') }}">
                      @if($errors->has("how_register"))
                        <span class="text-muted help-block">{{ $errors->first("how_register") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_degree')) has-error @endif">
                <label class="col-sm-3 text-left">شروط الحصول على الشهادة:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_degree"  value="{{ old('how_degree') }}">
                      @if($errors->has("how_degree"))
                        <span class="text-muted help-block">{{ $errors->first("how_degree") }}</span>
                      @endif
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="pull-left">
              <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                <a class="btn btn-danger mr-5" href="{{ route('courses.index') }}">&nbsp الغاء &nbsp</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </form>
@endsection
@section("scripts")
<script type="text/javascript">

  $(document).ready(function(){
    $(".add-more").click(function(e){
        e.preventDefault();
        var current = parseInt($('#count').val(), 10);
        var newInput = '<input id="field' + (current + 1) + '" name="goals[]" class="field form-control" >';
        var removeButton = '<button id="btn' + (current + 1) + '" class="field form-control btn btn-danger remove-me" >-</button>';
        $("#field" + current).after(newInput);
        $("#btn" + current).after(removeButton);
        current = current + 1;
        $("#count").val(current);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
                $("#count").val(parseInt($('#count').val(), 10) - 1);
            });
    });
    

    
});
</script>
@endsection

Laravel Project Education Center/resources/views/courses/edit.blade.php
@extends('layouts.admin')

@section('header')
   <h3 class="panel-title"><i class="glyphicon glyphicon-edit"></i> تعديل كورس {{ $course->name }}</h3>
@endsection
@section('css')
<style type="text/css">
  
  #field {
    margin-bottom:20px;
}
.add-more{
  background-color: green;
  color: #fff;
}
.remove-me,.add-more{
  display: inline;
  padding: 9px 20px;
}
.input{
  display: inline;
}
</style>
@endsection

@section('content')
    @include('error')
    <form class="form-horizontal mt-10" action="{{ route('courses.update', $course->id) }}" method="POST">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-body">
            @include('error')
            <div class="form-group @if($errors->has('name')) has-error @endif">
                <label class="col-sm-3 control-label text-left">إسم الكورس:<span class="asterisk"> *</span></label>
                <div class="col-sm-6">
                     <input required class="form-control" name="name" placeholder="أدخل اسم الكورس" value="{{ is_null(old('name')) ? $course->name : old('name') }}">
                      @if($errors->has("name"))
                        <span class="text-muted help-block">{{ $errors->first("name") }}</span>
                      @endif
                </div>
            </div>
            <div class="form-group @if($errors->has('department')) has-error @endif">
              <label class="col-sm-3 text-left" for="department-field">القسم:<span class="asterisk"> *</span></label>
              <div class="col-sm-6">
                <select id="department-field" name="department" class="form-control" >
                  <option value="0">Choose</option>
                  @foreach($departments as $department)
                    <option value="{{$department->id}}" @if($course->department->id==$department->id) selected @endif>{{$department->name}}</option>
                  @endforeach
                </select>
                @if($errors->has("department"))
                  <span class="help-block">{{ $errors->first("department") }}</span>
                @endif
              </div>
            </div>
            <div class="form-group @if($errors->has('description')) has-error @endif">
                <label class="col-sm-3 control-label text-left">نبذه عن الكورس:</label>
                <div class="col-sm-6">
                     <textarea  name="description" class="form-control" rows="3">{{ is_null(old('description')) ? $course->description : old('description') }}</textarea>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                </div>
            </div>
            <div class="form-group @if($errors->has('goals')) has-error @endif">
              <label class="col-sm-3 control-label text-left" for="goals-field">الأهداف:</label>
              <div class="col-sm-6 control-group" id="fields">
                  <input data-items="8" name="goals[]" class="form-control" value="{{ is_null(old('goals[]')) ? $course->goals : old('goals[]') }}"/>
                  @if($errors->has("goals"))
                    <span class="help-block">{{ $errors->first("goals") }}</span>
                  @endif
              </div>
              <button class="btn btn-success" type="button">+</button>
            </div>
             <div class="form-group @if($errors->has('age')) has-error @endif">
                <label class="col-sm-3 control-label text-left">المرحلة العمرية:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="age" value="{{ is_null(old('age')) ? $course->age : old('age') }}">
                      @if($errors->has("age"))
                        <span class="text-muted help-block">{{ $errors->first("age") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('duration')) has-error @endif">
                <label class="col-sm-3 control-label text-left">المدة الزمنية:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="duration" value="{{ is_null(old('duration')) ? $course->duration : old('duration') }}">
                      @if($errors->has("duration"))
                        <span class="text-muted help-block">{{ $errors->first("duration") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('levels')) has-error @endif">
                <label class="col-sm-3 control-label text-left">المستويات:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="levels" value="{{ is_null(old('levels')) ? $course->levels : old('levels') }}">
                      @if($errors->has("levels"))
                        <span class="text-muted help-block">{{ $errors->first("levels") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('tutorials')) has-error @endif">
                <label class="col-sm-3 control-label text-left">المناهج المستخدمة:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="tutorials" value="{{ is_null(old('tutorials')) ? $course->tutorials : old('tutorials') }}">
                      @if($errors->has("tutorials"))
                        <span class="text-muted help-block">{{ $errors->first("tutorials") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_performance')) has-error @endif">
                <label class="col-sm-3 control-label text-left">كيفية التقييم:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_performance" value="{{ is_null(old('how_performance')) ? $course->how_performance : old('how_performance') }}">
                      @if($errors->has("how_performance"))
                        <span class="text-muted help-block">{{ $errors->first("how_performance") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_register')) has-error @endif">
                <label class="col-sm-3 control-label text-left">شروط التسجيل:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_register" value="{{ is_null(old('how_register')) ? $course->how_register : old('how_register') }}">
                      @if($errors->has("how_register"))
                        <span class="text-muted help-block">{{ $errors->first("how_register") }}</span>
                      @endif
                </div>
            </div>
             <div class="form-group @if($errors->has('how_degree')) has-error @endif">
                <label class="col-sm-3 control-label text-left">شروط الحصول على الشهادة:</label>
                <div class="col-sm-6">
                     <input class="form-control" name="how_degree"  value="{{ is_null(old('how_degree')) ? $course->how_degree : old('how_degree') }}">
                      @if($errors->has("how_degree"))
                        <span class="text-muted help-block">{{ $errors->first("how_degree") }}</span>
                      @endif
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="pull-left">
              <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                <a class="btn btn-danger mr-5" href="{{ route('courses.index') }}">&nbsp الغاء &nbsp</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </form>
@endsection
@section("scripts")
<script type="text/javascript">

  $(document).ready(function(){
    var next = 1;
    $(".add-more").click(function(e){
        e.preventDefault();
        var addto = "#field" + next;
        var addRemove = "#field" + (next);
        next = next + 1;
        var newIn = '<label class="col-sm-2 control-label" for="goals-field">Goal '+ next +'</label>';
        newIn += '<input autocomplete="off" class="input form-control" id="field' + next + '" name="goals[]" type="text">';
        var newInput = $(newIn);
        var removeBtn = '<button id="remove' + (next - 1) + '" class="btn btn-danger remove-me" >-</button></div><div id="field">';
        var removeButton = $(removeBtn);
        $(addto).after(newInput);
        $(addRemove).after(removeButton);
        $("#field" + next).attr('data-source',$(addto).attr('data-source'));
        $("#count").val(next);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
    });
});
</script>
@endsection

Laravel Project Education Center/resources/views/courses/index.blade.php
@extends('layouts.admin')

@section('header')
    <h3 class="panel-title"><i class="glyphicon glyphicon-align-justify"></i> الدورات </h3>     
@endsection

@section('content')
<div class="panel">
        <div class="panel-heading">
            <div class="pull-left">
                <a class="btn btn-success" href="{{ route('courses.create') }}"><i class="glyphicon glyphicon-plus"></i> جديد</a>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        @if($courses->count())
        <div class="panel-body no-padding">
            <div class="table-responsive" style="margin-top: -1px;">
                <table class="table table-primary"">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 2%;">#</th>
                            <th class="text-right">إسم الدورة</th>
                            <th class="text-right">القسم</th>
                            <th class="text-right">نبذه عن الدورة</th>
                            <th class="text-center" style="width: 20%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td class="text-center border-right">{{$course->id}}</td>
                                <td>{{$course->name}}</td>
                                <td>{{$course->department->name}}</td>
                                <td>{{$course->description}}</td>
                                <td class="text-center">
                                    <a class="btn btn-xs btn-primary" href="{{ route('courses.show', $course->id) }}"><i class="glyphicon glyphicon-eye-open"></i> عرض</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('courses.edit', $course->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>
                                    <form action="{{ route('courses.destroy', $course->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                                    </form>
                                </td>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $courses->render() !!}
            </div>
        </div>
        @else
            <h3 class="text-center alert alert-info">لا يوجد دورات في الوقت الحالي!!</h3>
        @endif
    </div>
@endsection

Laravel Project Education Center/resources/views/courses/show.blade.php
@extends('layouts.admin')

@section('header')
        <h3 class="panel-title"><i class="glyphicon glyphicon-eye-open"></i> عرض كورس {{ $course->name }}</h3>
@endsection

@section('content')
    @include('error')
    <div class="panel">
        <div class="panel-heading">
            <div class="pull-right">
                <a class="btn btn-primary mr-5" href="{{ route('courses.index') }}"> القائمه الرئيسية</a>
            </div>
            <div class="pull-left">
                <a class="btn btn-warning" href="{{ route('courses.edit', $course->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>

                <form action="{{ route('courses.destroy', $course->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                </form>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        <div class="panel-body">
            <form class="form-horizontal mt-10" action="#">
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left " for="name-field">الإسم:</label>
                    <div class="col-sm-6">
                        <input id="name-field" class="form-control" readonly name="name" value="{{ $course->name}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left " for="name-field">القسم:</label>
                    <div class="col-sm-6">
                        <input id="department-field" class="form-control" readonly name="department" value="{{ $course->department->name}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">نبذه عن الكورس:</label>
                    <div class="col-sm-6">
                         <textarea  name="description" class="form-control" rows="3" readonly> {{ $course->description }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label text-left" for="goals-field">الأهداف:</label>
                  <div class="col-sm-6 control-group" id="fields">
                      <input data-items="8" name="goals[]" class="form-control" readonly value="{{ $course->goals }}" />
                  </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">المرحلة العمرية:</label>
                    <div class="col-sm-6">
                        <textarea  name="age" class="form-control" rows="3" readonly> {{ $course->age }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">المدة الزمنية:</label>
                    <div class="col-sm-6">
                         <textarea  name="duration" class="form-control" rows="3" readonly> {{ $course->duration }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">المستويات:</label>
                    <div class="col-sm-6">
                        <textarea  name="levels" class="form-control" rows="3" readonly> {{ $course->levels }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">المناهج المستخدمة:</label>
                    <div class="col-sm-6">
                        <textarea  name="tutorials" class="form-control" rows="3" readonly> {{ $course->tutorials }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">كيفية التقييم:</label>
                    <div class="col-sm-6">
                        <textarea  name="description" class="form-control" rows="3" readonly> {{ $course->how_performance }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">شروط التسجيل:</label>
                    <div class="col-sm-6">
                        <textarea  name="how_register" class="form-control" rows="3" readonly> {{ $course->how_register }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label text-left">شروط الحصول على الشهادة:</label>
                    <div class="col-sm-6">
                        <textarea  name="how_degree" class="form-control" rows="3" readonly> {{ $course->how_degree }}</textarea>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection