Laravel Project Education Center/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|register_adult
*/

Route::group(['middleware' => ['auth']], function () {
	Route::resource("feedback","FeedbackController");
	Route::get('/home', function () {
	    return view('home');
	});
});

Route::group(['middleware' => ['auth','customer']], function () {
	Route::get("allcourses","CourseController@allcourses"); 
	Route::get("customercourses/{key}","CourseController@customercourses"); 
	Route::get("allcamps","CustomerController@allcamps"); 
	Route::get("customercamps","CustomerController@customercamps"); 
	Route::get("customerconsultation","CustomerController@customerconsultation"); 
	Route::get("allconsultation","CustomerController@allconsultation"); 
	
	Route::get('/error', function()
	{
	   return view('errors');
	});

	Route::get("user_programs/{key}","ProgramController@user_programs");
	Route::get("view_course/{key}","ProgramController@view_course");

}); 

	Route::group(['middleware' => ['auth','admin']], function () {
		Route::resource("course_menus","CourseMenuController"); 
	Route::resource("menus","MenuController");
	Route::post("new_customer","UserController@create"); 
	Route::get("customers_user/{key}", function () {
	    return view('users.create');
	}); 
	Route::post("customers_adult","CustomerController@customers_adult"); 
	Route::get("/adult_application_create","AdultController@createApplication"); 
	Route::post("/adult_application_store","AdultController@storeApplication")->name("adult.application.store"); 
	Route::get("/kid_application_create","KidController@createApplication"); 
	Route::post("/kid_application_store","KidController@storeApplication")->name("kid.application.store"); 

	Route::get('/register_adult', function () {
		//$howKnows = App\HowKnow::all();
		//$jobs=App\Job::orderBy("id","asc")->get();,compact("howKnows","jobs");
	    return view('customers.register_adult');
	}); 
	Route::resource("users","UserController"); 
	Route::resource("customers","CustomerController"); 
	Route::resource("kids","KidController"); 
	Route::resource("departments","DepartmentController");
	Route::resource("parents","ParentController");
	Route::resource("kid_parents","KidParentController");
	Route::resource("jobs","JobController");
	Route::resource("adults","AdultController");
	Route::resource("adult_jobs","AdultJobController");
	Route::resource("courses","CourseController"); 
	Route::resource("favorites","FavoriteController");
	Route::resource("programs","ProgramController");
	Route::get("course_programs/{key}","ProgramController@course_programs");


	Route::resource("roles","RoleController");
	Route::resource("employees","EmployeeController"); 
	Route::resource("program_employees","ProgramEmployeeController");
	Route::resource("department_employees","DepartmentEmployeeController");
	Route::resource("customer_programs","CustomerProgramController");
	Route::get("customer_program/{key}","CustomerProgramController@listbyProgram");
	Route::get("how_know_customers/{key}","CustomerController@listByHowKnow");
	Route::resource("how_knows","HowKnowController");
	Route::get('/dashboard', function () {
	    return view('welcome');
	});
	Route::get('/page-error', function()
	{
	   return view('error-admin');
	});
	Route::resource("levels","LevelController");
	Route::resource("lectures","LectureController");
	Route::resource("program_levels","ProgramLevelController");
	Route::resource("lecture_customer_programs","LectureCustomerProgramController");
	//Route::get('/home', 'HomeController@index');
});
Auth::routes();
Route::get('/', function()
	{
	   return view('auth.login');
	});
Route::get('logout', array('uses' => 'HomeController@logout'));

Laravel Project Education Center/app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
}

Laravel Project Education Center/app/Http/Controllers/RoleController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$roles = Role::orderBy('id', 'desc')->paginate(10);

		return view('roles.index', compact('roles'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('roles.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
    	$this->validate($request, [
	        'name' => 'required|max:255|unique:roles',
    	]);
		$role = new Role();

		$role->name = $request->input("name");

		$role->save();

		return redirect()->route('roles.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$role = Role::findOrFail($id);

		return view('roles.show', compact('role'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		
		$role = Role::findOrFail($id);

		return view('roles.edit', compact('role'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$this->validate($request, [
	        'name' => 'required|max:255|unique:roles,name,'.$id,
    	]);
		$role = Role::findOrFail($id);

		$role->name = $request->input("name");

		$role->save();

		return redirect()->route('roles.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$role = Role::findOrFail($id);
		$role->delete();

		return redirect()->route('roles.index')->with('message', 'Item deleted successfully.');
	}

}

Laravel Project Education Center/resources/views/roles/create.blade.php
@extends('layouts.admin')

 @section('header')
    <h3 class="panel-title"><i class="glyphicon glyphicon-plus"></i> وظيفه جديد</h3>
@endsection
@section('content')

   <form class="form-horizontal mt-10" action="{{ route('roles.store') }}" method="POST">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-body">
            @include('error')
            <div class="form-group @if($errors->has('name')) has-error @endif">
                <label class="control-label col-sm-3 text-left">إسم الوظيفه:<span class="asterisk"> *</span></label>
                <div class="col-sm-6">
                   <input required class="form-control" name="name" placeholder="أدخل إسم الوظيفه" value="{{ old('name') }}">
                    @if($errors->has("name"))
                      <span class="text-muted help-block">{{ $errors->first("name") }}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="pull-left">
                <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                <a class="btn btn-danger mr-5" href="{{ route('roles.index') }}">&nbsp الغاء &nbsp</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </form>
@endsection

Laravel Project Education Center/resources/views/roles/edit.blade.php
@extends('layouts.admin')

@section('header')
        <h3 class="panel-title"><i class="glyphicon glyphicon-edit"></i> تعديل وظيفه {{ $role->name }}</h3>
@endsection

@section('content')
    @include('error')

      <form class="form-horizontal mt-10" action="{{ route('roles.update', $role->id) }}" method="POST">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="form-body">
                @include('error')
                <div class="form-group @if($errors->has('name')) has-error @endif">
                    <label class="col-sm-3 control-label text-left " for="name-field">إسم الوظيفه:<span class="asterisk"> *</span></label>
                    <div class="col-sm-6">
                        <input required type="text" id="name-field" class="form-control input-sm" name="name" value="{{ is_null(old('name')) ? $role->name : old('name') }}">
                        @if($errors->has("name"))
                          <span class="text-muted help-block">{{ $errors->first("name") }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="form-footer">
                <div class="pull-left">
                    <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                    <a class="btn btn-danger mr-5" href="{{ route('roles.index') }}">&nbsp إلغاء &nbsp</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </form>
    
@endsection

Laravel Project Education Center/resources/views/roles/index.blade.php
@extends('layouts.admin')

@section('header')
    <h3 class="panel-title"><i class="glyphicon glyphicon-align-justify"></i> الوظائف </h3>
@endsection

@section('content')

   <div class="panel">
        <div class="panel-heading">
            <div class="pull-left">
                <a class="btn btn-success" href="{{ route('roles.create') }}"><i class="glyphicon glyphicon-plus"></i> جديد</a>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        @if($roles->count())
        <div class="panel-body no-padding">
            <div class="table-responsive" style="margin-top: -1px;">
                <table class="table table-primary"">
                    <thead>
                        <tr>
                            <th class="text-right">الوظيفه</th>
                            <th class="text-center" style="width: 25%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($roles as $role)
                            <tr>
                                <td>{{$role->name}}</td>
                                <td class="text-center border-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('roles.show',
                                        $role->id) }}"><i class="glyphicon glyphicon-eye-open"></i> عرض</a>
                                        
                                    <a class="btn btn-xs btn-warning" href="{{ route('roles.edit', $role->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>

                                    <form action="{{ route('roles.destroy', $role->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @else
            <h3 class="text-center alert alert-info">لا يوجد وظائف في الوقت الحالي!</h3>
        @endif
    </div>
@endsection

Laravel Project Education Center/resources/views/roles/show.blade.php
@extends('layouts.admin')

@section('header')
        <h3 class="panel-title"><i class="glyphicon glyphicon-eye-open"></i> عرض وظيفة {{ $role->name }}</h3>
@endsection

@section('content')
    @include('error')
    <div class="panel">
        <div class="panel-heading">
            <div class="pull-right">
                <a class="btn btn-primary mr-5" href="{{ route('roles.index') }}"> القائمه الرئيسية</a>
            </div>
            <div class="pull-left">
                <a class="btn btn-warning" href="{{ route('roles.edit', $role->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>

                <form action="{{ route('roles.destroy', $role->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                </form>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-3 control-label text-left " for="name-field">إسم الوظيفه:<span class="asterisk"> *</span></label>
                <div class="col-sm-6">
                    <input required type="text" id="name-field" class="form-control input-sm" readonly name="name" value="{{ $role->name}}">
                </div>
            </div>
        </div>
    </div>
@endsection