Laravel Project Education Center/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|register_adult
*/

Route::group(['middleware' => ['auth']], function () {
	Route::resource("feedback","FeedbackController");
	Route::get('/home', function () {
	    return view('home');
	});
});

Route::group(['middleware' => ['auth','customer']], function () {
	Route::get("allcourses","CourseController@allcourses"); 
	Route::get("customercourses/{key}","CourseController@customercourses"); 
	Route::get("allcamps","CustomerController@allcamps"); 
	Route::get("customercamps","CustomerController@customercamps"); 
	Route::get("customerconsultation","CustomerController@customerconsultation"); 
	Route::get("allconsultation","CustomerController@allconsultation"); 
	
	Route::get('/error', function()
	{
	   return view('errors');
	});

	Route::get("user_programs/{key}","ProgramController@user_programs");
	Route::get("view_course/{key}","ProgramController@view_course");

}); 

	Route::group(['middleware' => ['auth','admin']], function () {
		Route::resource("course_menus","CourseMenuController"); 
	Route::resource("menus","MenuController");
	Route::post("new_customer","UserController@create"); 
	Route::get("customers_user/{key}", function () {
	    return view('users.create');
	}); 
	Route::post("customers_adult","CustomerController@customers_adult"); 
	Route::get("/adult_application_create","AdultController@createApplication"); 
	Route::post("/adult_application_store","AdultController@storeApplication")->name("adult.application.store"); 
	Route::get("/kid_application_create","KidController@createApplication"); 
	Route::post("/kid_application_store","KidController@storeApplication")->name("kid.application.store"); 

	Route::get('/register_adult', function () {
		//$howKnows = App\HowKnow::all();
		//$jobs=App\Job::orderBy("id","asc")->get();,compact("howKnows","jobs");
	    return view('customers.register_adult');
	}); 
	Route::resource("users","UserController"); 
	Route::resource("customers","CustomerController"); 
	Route::resource("kids","KidController"); 
	Route::resource("departments","DepartmentController");
	Route::resource("parents","ParentController");
	Route::resource("kid_parents","KidParentController");
	Route::resource("jobs","JobController");
	Route::resource("adults","AdultController");
	Route::resource("adult_jobs","AdultJobController");
	Route::resource("courses","CourseController"); 
	Route::resource("favorites","FavoriteController");
	Route::resource("programs","ProgramController");
	Route::get("course_programs/{key}","ProgramController@course_programs");


	Route::resource("roles","RoleController");
	Route::resource("employees","EmployeeController"); 
	Route::resource("program_employees","ProgramEmployeeController");
	Route::resource("department_employees","DepartmentEmployeeController");
	Route::resource("customer_programs","CustomerProgramController");
	Route::get("customer_program/{key}","CustomerProgramController@listbyProgram");
	Route::get("how_know_customers/{key}","CustomerController@listByHowKnow");
	Route::resource("how_knows","HowKnowController");
	Route::get('/dashboard', function () {
	    return view('welcome');
	});
	Route::get('/page-error', function()
	{
	   return view('error-admin');
	});
	Route::resource("levels","LevelController");
	Route::resource("lectures","LectureController");
	Route::resource("program_levels","ProgramLevelController");
	Route::resource("lecture_customer_programs","LectureCustomerProgramController");
	//Route::get('/home', 'HomeController@index');
});
Auth::routes();
Route::get('/', function()
	{
	   return view('auth.login');
	});
Route::get('logout', array('uses' => 'HomeController@logout'));

Laravel Project Education Center/app/CustomerProgram.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CustomerProgram extends Model
{
    //
    public function program(){
    	return $this->belongsTo("App\Program","program_id");
    }
    public function customer(){
    	return $this->belongsTo("App\Customer","customer_id");
    }
}

Laravel Project Education Center/app/Http/Controllers/CustomerProgramController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Customer;
use App\Adult;
use App\kid;
use App\Program;
use App\CustomerProgram;
use Illuminate\Http\Request;

class CustomerProgramController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$customer_programs = CustomerProgram::orderBy('id', 'desc')->paginate(15);

		return view('customer_programs.index', compact('customer_programs'));
	}

	public function listbyProgram($id)
	{
		$customer_programs = CustomerProgram::where('program_id',$id)->orderBy('id', 'desc')->paginate(15);

		return view('customer_programs.index', compact('customer_programs'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$programs = Program::all();
		return view('customer_programs.create',compact('programs'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{

		//var_dump(session("adult"));
	

		$customer_program = new CustomerProgram();

		$customer_program->customer_id = $request->customer_id;
        $customer_program->program_id = $request->program_id;
        $customer_program->goals = $request->goals;
       // $customer_program->status = $request->input("status");

		$customer_program->save();

		return redirect('allcourses')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$customer_program = CustomerProgram::findOrFail($id);

		return view('customer_programs.show', compact('customer_program'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$customer_program = CustomerProgram::findOrFail($id);

		return view('customer_programs.edit', compact('customer_program'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$customer_program = CustomerProgram::findOrFail($id);

		$customer_program->customer_id = $request->input("customer_id");
        $customer_program->program_id = $request->input("program_id");
        $customer_program->goals = $request->input("goals");
        $customer_program->status = $request->input("status");

		$customer_program->save();

		return redirect()->route('customer_programs.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$customer_program = CustomerProgram::findOrFail($id);
		$customer_program->delete();

		return redirect()->route('customer_programs.index')->with('message', 'Item deleted successfully.');
	}

}

Laravel Project Education Center/resources/views/customer_programs/create.blade.php
@extends('layouts.admin')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
  <i class="glyphicon glyphicon-plus"></i> Customer Programs 

@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('customer_programs.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div hidden class="form-group @if($errors->has('customer_id')) has-error @endif">
                       <label class="col-sm-2 control-label" for="customer_id-field">Customer_id</label>
                    <input type="text" id="customer_id-field" name="customer_id" class="form-control txt-new" value="{{ old("customer_id") }}"/>
                       @if($errors->has("customer_id"))
                        <span class="help-block">{{ $errors->first("customer_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('program_id')) has-error @endif">
                       <label class="col-sm-2 control-label" for="program_id-field">Program</label>
                    <select id="program_id-field" name="program_id" class="txt-new" >
                      @if($programs->count() >0)
                        @foreach($programs as $program)
                          <option value="{{$program->id}}"> {{$program->course->name}}</option>
                        @endforeach
                      @endif
                    </select>
                       @if($errors->has("program_id"))
                        <span class="help-block">{{ $errors->first("program_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('goals')) has-error @endif">
                       <label class="col-sm-2 control-label" for="goals-field">Goals</label>
                    <textarea class="form-control txt-new" id="goals-field" rows="3" name="goals">{{ old("goals") }}</textarea>
                       @if($errors->has("goals"))
                        <span class="help-block">{{ $errors->first("goals") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label class="col-sm-2 control-label" for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control txt-new" value="{{ old("status") }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('customer_programs.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

Laravel Project Education Center/resources/views/customer_programs/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> CustomerPrograms / Edit #{{$customer_program->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('customer_programs.update', $customer_program->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('customer_id')) has-error @endif">
                       <label for="customer_id-field">Customer_id</label>
                    <input type="text" id="customer_id-field" name="customer_id" class="form-control" value="{{ is_null(old("customer_id")) ? $customer_program->customer_id : old("customer_id") }}"/>
                       @if($errors->has("customer_id"))
                        <span class="help-block">{{ $errors->first("customer_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('program_id')) has-error @endif">
                       <label for="program_id-field">Program_id</label>
                    <input type="text" id="program_id-field" name="program_id" class="form-control" value="{{ is_null(old("program_id")) ? $customer_program->program_id : old("program_id") }}"/>
                       @if($errors->has("program_id"))
                        <span class="help-block">{{ $errors->first("program_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('goals')) has-error @endif">
                       <label for="goals-field">Goals</label>
                    <textarea class="form-control" id="goals-field" rows="3" name="goals">{{ is_null(old("goals")) ? $customer_program->goals : old("goals") }}</textarea>
                       @if($errors->has("goals"))
                        <span class="help-block">{{ $errors->first("goals") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status')) has-error @endif">
                       <label for="status-field">Status</label>
                    <input type="text" id="status-field" name="status" class="form-control" value="{{ is_null(old("status")) ? $customer_program->status : old("status") }}"/>
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('customer_programs.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

Laravel Project Education Center/resources/views/customer_programs/index.blade.php
@extends('layouts.admin')

@section('header')
      <h3>    <i class="glyphicon glyphicon-align-justify"></i> الطلاب الملتحقين بالبرنامج  </h3>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($customer_programs->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                        <th class="text-right">الطالب</th>
                        <th class="text-right">البرنامج</th>
                        <th class="text-right">الأهداف</th>
                        <th class="text-center">الحالة</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($customer_programs as $customer_program)
                            <tr>
                                <td><a href="{{ route('customers.show', $customer_program->customer->id) }}">{{$customer_program->customer->name}} </a></td>
                                <td>{{$customer_program->program->course->name}}</td>
                                <td>{{$customer_program->goals}}</td>
                                <td class="text-center">{{$customer_program->status}}</td>
                              <!--  <td class="text-right">
                                    <a class="btn  btn-primary" href="{{ route('customer_programs.show', $customer_program->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn  btn-warning" href="{{ route('customer_programs.edit', $customer_program->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('customer_programs.destroy', $customer_program->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn  btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                                -->
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $customer_programs->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

Laravel Project Education Center/resources/views/customer_programs/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>CustomerPrograms / Show #{{$customer_program->id}}</h1>
        <form action="{{ route('customer_programs.destroy', $customer_program->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('customer_programs.edit', $customer_program->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="customer_id">CUSTOMER_ID</label>
                     <p class="form-control-static">{{$customer_program->customer_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="program_id">PROGRAM_ID</label>
                     <p class="form-control-static">{{$customer_program->program_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="goals">GOALS</label>
                     <p class="form-control-static">{{$customer_program->goals}}</p>
                </div>
                    <div class="form-group">
                     <label for="status">STATUS</label>
                     <p class="form-control-static">{{$customer_program->status}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('customer_programs.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection

Laravel Project Education Center/resources/views/customer_programs/user_programs.blade.php
@extends('layouts.customer-admin')

@section('header')
      <p class="lead">برامجي</p>
   
@endsection

@section('content')
                    <div class="row">
                        <div class="col-md-12">

                            <!-- Start color horizontal tabs -->
                            <div class="panel panel-tab panel-tab-double shadow">
                                <!-- Start tabs heading -->
                                <div class="panel-heading no-padding">
                                    <ul class="nav nav-tabs">
                                        <li class="active nav-border nav-border-top-danger">
                                            <a href="#tab6-1" data-toggle="tab" class="text-center">
                                                الحالية
                                            </a>
                                        </li>
                                        <li class="nav-border nav-border-top-primary">
                                            <a href="#tab6-2" data-toggle="tab" class="text-center">
                                                القادمة
                                            </a>
                                        </li>
                                        <li class="nav-border nav-border-top-success">
                                            <a href="#tab6-3" data-toggle="tab" class="text-center">
                                                المنتهية
                                            </a>
                                        </li>
                                        <li class="nav-border nav-border-top-info">
                                            <a href="#tab6-4" data-toggle="tab" class="text-center">
                                                المفضلة
                                            </a>
                                        </li>
                                       
                                    </ul>
                                </div><!-- /.panel-heading -->
                                <!--/ End tabs heading -->

                                <!-- Start tabs content -->
                                <div class="panel-body">
                                    <div class="tab-content">
                                        <div class="tab-pane fade in active" id="tab6-1">
                                        @if(count($currently_programs) >0)
                                           
                                           @foreach($currently_programs as $program)

                                          <p><a href="{{URL::asset('view_course/'.$program->id)}}"> {{$program->course->name}}</a></p>
                                           

                                           @endforeach
                                           @endif
                                        </div>
                                        <div class="tab-pane fade" id="tab6-2">
                                            
                                            @if(count($next_programs) >0)
                                           
                                           @foreach($next_programs as $program)
<p><a href="{{URL::asset('view_course/'.$program->id)}}"> {{$program->course->name}}</a></p>
                                           

                                           @endforeach
                                           @endif
                                        </div>
                                        <div class="tab-pane fade" id="tab6-3">
                                            @if(count($done_programs) >0)
                                           
                                           @foreach($done_programs as $program)
                                           <p><a href="{{URL::asset('view_course/'.$program->id)}}"> {{$program->course->name}}</a></p>
                                           

                                           @endforeach
                                           @endif
                                        </div>
                                        <div class="tab-pane fade" id="tab6-4">
                                            @if(count($favorites) >0)
                                           
                                           @foreach($favorites as $program)

                                           <p><a href="{{URL::asset('view_course/'.$program->id)}}"> {{$program->name}}</a></p>
                                           

                                           @endforeach
                                           @endif
                                        </div>
                                       
                                    </div>
                                </div><!-- /.panel-body -->
                                <!--/ End tabs content -->
                            </div><!-- /.panel -->
                            <!--/ End color horizontal tabs -->

                        </div>
                    </div>

@endsection

Laravel Project Education Center/resources/views/customer_programs/view_course.blade.php
@extends('layouts.customer-admin')

@section('header')
      <p class="lead">برامجي</p>
   
@endsection

@section('content')
                    <div class="row">
                        <div class="col-md-12">

                            <!-- Start color horizontal tabs -->
                            <div class="panel panel-tab panel-tab-double shadow">
                                <!-- Start tabs heading -->
                                <div class="panel-heading no-padding">
                                    <ul class="nav nav-tabs">
                                    @if($menus)
                                    <?php  $i=0; ?>
                                      @foreach($menus as $menu)
                                      @if($i == 0)
                                        <li class="active nav-border nav-border-top-{{$menu->class_name}}">
                                        @else
                                        <li class=" nav-border nav-border-top-{{$menu->class_name}}">

                                        @endif
                                            <a href="#tab_{{$menu->id}}" data-toggle="tab" class="text-center">
                                                {{$menu->name}}
                                            </a>
                                        </li>

                                    <?php  $i++; ?>

                                        
                                       @endforeach
                                       @endif
                                    </ul>
                                </div><!-- /.panel-heading -->
                                <!--/ End tabs heading -->

                                <!-- Start tabs content -->
                                <div class="panel-body">
                                    <div class="tab-content">
                                    @if($menus)
                                      @foreach($menus as $menu)
                                        <div class="tab-pane fade in active" id="tab_{{$menu->id}}">
                                        @include($menu->view)
                                          
                                        </div>
                                       @endforeach
                                       @endif

                                    </div>
                                </div><!-- /.panel-body -->
                                <!--/ End tabs content -->
                            </div><!-- /.panel -->
                            <!--/ End color horizontal tabs -->

                        </div>
                    </div>

@endsection