Laravel Project Education Center/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|register_adult
*/

Route::group(['middleware' => ['auth']], function () {
	Route::resource("feedback","FeedbackController");
	Route::get('/home', function () {
	    return view('home');
	});
});

Route::group(['middleware' => ['auth','customer']], function () {
	Route::get("allcourses","CourseController@allcourses"); 
	Route::get("customercourses/{key}","CourseController@customercourses"); 
	Route::get("allcamps","CustomerController@allcamps"); 
	Route::get("customercamps","CustomerController@customercamps"); 
	Route::get("customerconsultation","CustomerController@customerconsultation"); 
	Route::get("allconsultation","CustomerController@allconsultation"); 
	
	Route::get('/error', function()
	{
	   return view('errors');
	});

	Route::get("user_programs/{key}","ProgramController@user_programs");
	Route::get("view_course/{key}","ProgramController@view_course");

}); 

	Route::group(['middleware' => ['auth','admin']], function () {
		Route::resource("course_menus","CourseMenuController"); 
	Route::resource("menus","MenuController");
	Route::post("new_customer","UserController@create"); 
	Route::get("customers_user/{key}", function () {
	    return view('users.create');
	}); 
	Route::post("customers_adult","CustomerController@customers_adult"); 
	Route::get("/adult_application_create","AdultController@createApplication"); 
	Route::post("/adult_application_store","AdultController@storeApplication")->name("adult.application.store"); 
	Route::get("/kid_application_create","KidController@createApplication"); 
	Route::post("/kid_application_store","KidController@storeApplication")->name("kid.application.store"); 

	Route::get('/register_adult', function () {
		//$howKnows = App\HowKnow::all();
		//$jobs=App\Job::orderBy("id","asc")->get();,compact("howKnows","jobs");
	    return view('customers.register_adult');
	}); 
	Route::resource("users","UserController"); 
	Route::resource("customers","CustomerController"); 
	Route::resource("kids","KidController"); 
	Route::resource("departments","DepartmentController");
	Route::resource("parents","ParentController");
	Route::resource("kid_parents","KidParentController");
	Route::resource("jobs","JobController");
	Route::resource("adults","AdultController");
	Route::resource("adult_jobs","AdultJobController");
	Route::resource("courses","CourseController"); 
	Route::resource("favorites","FavoriteController");
	Route::resource("programs","ProgramController");
	Route::get("course_programs/{key}","ProgramController@course_programs");


	Route::resource("roles","RoleController");
	Route::resource("employees","EmployeeController"); 
	Route::resource("program_employees","ProgramEmployeeController");
	Route::resource("department_employees","DepartmentEmployeeController");
	Route::resource("customer_programs","CustomerProgramController");
	Route::get("customer_program/{key}","CustomerProgramController@listbyProgram");
	Route::get("how_know_customers/{key}","CustomerController@listByHowKnow");
	Route::resource("how_knows","HowKnowController");
	Route::get('/dashboard', function () {
	    return view('welcome');
	});
	Route::get('/page-error', function()
	{
	   return view('error-admin');
	});
	Route::resource("levels","LevelController");
	Route::resource("lectures","LectureController");
	Route::resource("program_levels","ProgramLevelController");
	Route::resource("lecture_customer_programs","LectureCustomerProgramController");
	//Route::get('/home', 'HomeController@index');
});
Auth::routes();
Route::get('/', function()
	{
	   return view('auth.login');
	});
Route::get('logout', array('uses' => 'HomeController@logout'));

Laravel Project Education Center/app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    //
}

Laravel Project Education Center/app/Http/Controllers/JobController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Job;
use Illuminate\Http\Request;

class JobController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$jobs = Job::orderBy('id', 'desc')->paginate(10);

		return view('jobs.index', compact('jobs'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('jobs.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
	        'name' => 'required|unique:jobs|max:255',
    	]);
		$job = new Job();

		$job->name = $request->input("name");

		$job->save();

		return redirect()->route('jobs.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$job = Job::findOrFail($id);

		return view('jobs.show', compact('job'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{

		$job = Job::findOrFail($id);

		return view('jobs.edit', compact('job'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$this->validate($request, [
	        'name' => 'required|max:255|unique:jobs,name,'.$id,
    	]);
		$job = Job::findOrFail($id);

		$job->name = $request->input("name");

		$job->save();

		return redirect()->route('jobs.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$job = Job::findOrFail($id);
		$job->delete();

		return redirect()->route('jobs.index')->with('message', 'Item deleted successfully.');
	}

}

Laravel Project Education Center/resources/views/jobs/create.blade.php
@extends('layouts.admin')

 @section('header')
    <h3 class="panel-title"><i class="glyphicon glyphicon-plus"></i> وظيفة عملاء جديده</h3>
@endsection
@section('content')

   <form class="form-horizontal mt-10" action="{{ route('jobs.store') }}" method="POST">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-body">
            @include('error')
            <div class="form-group @if($errors->has('name')) has-error @endif">
                <label class="control-label col-sm-3 text-left">إسم الوظيفة:<span class="asterisk"> *</span></label>
                <div class="col-sm-6">
                   <input required class="form-control" name="name" placeholder="أدخل إسم الوظيفه" value="{{ old('name') }}">
                    @if($errors->has("name"))
                      <span class="text-muted help-block">{{ $errors->first("name") }}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="pull-left">
                <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                <a class="btn btn-danger mr-5" href="{{ route('jobs.index') }}">&nbsp الغاء &nbsp</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </form>
@endsection

Laravel Project Education Center/resources/views/jobs/edit.blade.php
@extends('layouts.admin')

@section('header')
        <h3 class="panel-title"><i class="glyphicon glyphicon-edit"></i> تعديل وظيفة {{ $job->name }} </h3>
@endsection

@section('content')
    @include('error')

      <form class="form-horizontal mt-10" action="{{ route('jobs.update', $job->id) }}" method="POST">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="form-body">
                @include('error')
                <div class="form-group @if($errors->has('name')) has-error @endif">
                    <label class="col-sm-3 control-label text-left " for="name-field">إسم الوظيفه:<span class="asterisk"> *</span></label>
                    <div class="col-sm-6">
                        <input required type="text" id="name-field" class="form-control input-sm" name="name" value="{{ is_null(old('name')) ? $job->name : old('name') }}">
                        @if($errors->has("name"))
                          <span class="text-muted help-block">{{ $errors->first("name") }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="form-footer">
                <div class="pull-left">
                    <button class="btn btn-success" type="submit">&nbsp حفظ &nbsp</button>
                    <a class="btn btn-danger mr-5" href="{{ route('jobs.index') }}">&nbsp إلغاء &nbsp</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </form>
    
@endsection

Laravel Project Education Center/resources/views/jobs/index.blade.php
@extends('layouts.admin')

@section('header')
    <h3 class="panel-title"><i class="glyphicon glyphicon-align-justify"></i> وظائف العملاء </h3>
@endsection

@section('content')
    <div class="panel">
        <div class="panel-heading">
            <div class="pull-left">
                <a class="btn btn-success" href="{{ route('jobs.create') }}"><i class="glyphicon glyphicon-plus"></i> جديد</a>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        @if($jobs->count())
        <div class="panel-body no-padding">
            <div class="table-responsive" style="margin-top: -1px;">
                <table class="table table-primary"">
                    <thead>
                        <tr>
                            <th class="text-right">إسم الوظيفه</th>
                            <th class="text-center" style="width: 25%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($jobs as $job)
                            <tr>
                                <td>{{$job->name}}</td>
                                <td class="text-center border-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('jobs.show',
                                        $job->id) }}"><i class="glyphicon glyphicon-eye-open"></i> عرض</a>
                                        
                                    <a class="btn btn-xs btn-warning" href="{{ route('jobs.edit', $job->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>

                                    <form action="{{ route('jobs.destroy', $job->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @else
            <h3 class="text-center alert alert-info">لا يوجد وظائف في الوقت الحالي!</h3>
        @endif
    </div>
@endsection

Laravel Project Education Center/resources/views/jobs/show.blade.php
@extends('layouts.admin')

@section('header')
        <h3 class="panel-title"><i class="glyphicon glyphicon-eye-open"></i> تعديل وظيفة {{ $job->name }} </h3>
@endsection

@section('content')
    @include('error')
    <div class="panel">
        <div class="panel-heading">
            <div class="pull-right">
                <a class="btn btn-primary mr-5" href="{{ route('jobs.index') }}"> القائمه الرئيسية</a>
            </div>
            <div class="pull-left">
                <a class="btn btn-warning" href="{{ route('jobs.edit', $job->id) }}"><i class="glyphicon glyphicon-edit"></i> تعديل</a>

                <form action="{{ route('jobs.destroy', $job->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> حذف</button>
                </form>
            </div>
            <div class="clearfix"></div>
        </div><!-- /.panel-heading -->
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-3 control-label text-left " for="name-field">إسم الوظيفه:<span class="asterisk"> *</span></label>
                <div class="col-sm-6">
                    <input required type="text" id="name-field" class="form-control input-sm" readonly name="name" value="{{ $job->name}}">
                </div>
            </div>
        </div>
    </div>
@endsection